apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-psql-pv
spec:
  capacity:
    storage: {{ .Values.persistence.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.persistence.hostPath }}"
