apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-psql-pv
spec:
  capacity:
    storage: {{ .Values.persistence.storage }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/vg01-lv01/psql-data
    server: 192.168.60.234
