apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-psql-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.psql.password | b64enc }}
  .dockerconfigjson: {{ .Values.harbor.dockerconfigjson | b64enc }}
