apiVersion: v1
kind: ConfigMap
metadata:
  name: appsc-config
  namespace: 13zp
data:
#  UPLOAD_PORT: "8080"
  DIRECTION: "BIDIRECTIONAL"
  MASTER: "true"
  JAVA_OPTS: "-Dserver.tomcat.mbeanregistry.enabled=true -Dserver.tomcat.max-connections=2000 -Dserver.tomcat.max-threads=200 -Dserver.connection-timeout=1200000 -Djavamelody.enabled=false -Doauth2.general.token.access.expirationTime=14400 -Doauth2.general.token.refresh.expirationTime=144000 -Dspring.datasource.hikari.connection-timeout=120000 -Dlogging.level.com.zaxxer.hikari.HikariConfig=DEBUG -Dlogging.level.com.zaxxer.hikari=DEBUG"
  SPRING_DATASOURCE_JDBC_HIKARI_URL: "jdbc:postgresql://192.168.45.16:5436/storagedb?targetServerType=master&loginTimeout=10&connectTimeout=10&tcpKeepAlive=true"
  SPRING_DATASOURCE_HIKARI_URL: "jdbc:postgresql://192.168.45.16:5436/storagedb?targetServerType=master&loginTimeout=10&connectTimeout=10&tcpKeepAlive=true"
  CONTEX_PATH: "/storage"
  PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  CATALINA_BASE: "/usr/local/sce"
  LANGUAGE: "ru_RU.UTF-8"
  LANG: "ru_RU.UTF-8"
  LC_ALL: "ru_RU.UTF-8"
  FILE_CONCAT_THREAD_COUNT: "6"
  THREAD_POOL_COMMON_THREAD_COUNT: "12"
  THREAD_POOL_COMMON_QUEUE_CAPACITY: "25000"
  TOMCAT_COMMON_MAX_THREADS: "200"
  UPLOAD_MAX_THREADS: "25"
  LIQUIBASE_CONTEXTS: "init,prod"
  HIKARI_MAX_POOL_SIZE: "100"
