apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-appsc-pv
spec:
  capacity:
    storage: {{ .Values.persistence.storage }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/sce-data
    server: 192.168.60.234
