apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-appsc-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes:
    {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
    {{- end }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
